version: '2'
services:
 alpine:
  build:
   context: alpine
   args:
    auth: jepson
    email: wjp13671142513@163.com
  image: jepson/alpine_1
  container_name: alpine_1
  restart: 'no'

 store:
  build:
   context: store
   args:
    auth: jepson
    email: wjp13671142513@163.com
  image: jepson/store_1
  container_name: store_1
  depends_on:
   - alpine
  volumes:
   - C:\Users\wjp13\projects\data:/data
  restart: always

 memcached:
  build:
   context: memcached
   args:
    auth: jepson
    email: wjp13671142513@163.com
  image: jepson/memcached_1
  container_name: memcached_1
  depends_on:
   - alpine
  restart: always

 php:
  build:
   context: php
   args:
    auth: jepson
    email: wjp13671142513@163.com
  image: jepson/php_1
  container_name: php_1
  depends_on:
   - alpine
   - store
   - memcached
  links:
   - memcached
  volumes:
   - /data/docker/php/:/app
  volumes_from:
   - store
  restart: always

 nginx:
  build:
   context: nginx
   args:
    auth: jepson
    email: wjp13671142513@163.com
  image: jepson/nginx_1
  container_name: nginx_1
  depends_on:
   - alpine
   - store
   - php
  links:
   - php
  volumes:
   - /data/docker/nginx/:/app
  volumes_from:
   - store
  ports:
   - 80:80
  restart: always