version: '2'
services:
 alpine:
  build:
   context: alpine
  image: %auth%/alpine%suffix%
  container_name: alpine%suffix%
  restart: 'no'

 store:
  build:
   context: store
  image: %auth%/store%suffix%
  container_name: store%suffix%
  depends_on:
   - alpine
  volumes:
   - %store_data%:/data
  restart: always

 memcached:
  build:
   context: memcached
  image: %auth%/memcached%suffix%
  container_name: memcached%suffix%
  depends_on:
   - alpine
  restart: always

 php:
  build:
   context: php
  image: %auth%/php%suffix%
  container_name: php%suffix%
  depends_on:
   - alpine
   - store
   - memcached
  links:
   - memcached
  volumes:
   - %php_app%:/app
  volumes_from:
   - store
  restart: always

 nginx:
  build:
   context: nginx
  image: %auth%/nginx%suffix%
  container_name: nginx%suffix%
  depends_on:
   - alpine
   - store
   - php
  links:
   - php
  volumes:
   - %nginx_app%:/app
  volumes_from:
   - store
  ports:
   - 80:80
  restart: always